export const PLATFORM_EVENT_TYPES = [
  "page_view",
  "calculator_opened",
  "calculator_started",
  "calculator_quote_displayed",
  "calculator_quote_success",
  "calculator_quote_failed",
  "api_usage_distance_matrix",
  "api_usage_geocode",
  "api_usage_autocomplete",
  "api_usage_route_calculation",
  "form_validation_error",
  "click_reserver",
  "click_devis",
  "click_contact",
  "click_phone",
  "click_email",
  "click_payment",
  "contact_form_started",
  "booking_form_started",
  "quote_form_started",
  "quote_request_created",
  "booking_created",
  "pro_login_success",
  "pro_login_failed",
  "pro_settings_saved",
  "payment_checkout_created",
  "payment_succeeded",
  "payment_failed",
  "stripe_webhook_received",
  "email_sent",
  "email_failed",
  "api_error",
  "admin_error",
  "platform_admin_login_success",
  "platform_admin_login_failed",
] as const;

export type PlatformEventType = (typeof PLATFORM_EVENT_TYPES)[number];

